import type { Metadata } from "next";
import SessionWrapper from "@/components/session-provider";

import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <SessionWrapper>
                    {children}
                    <Toaster />
                </SessionWrapper>
            </body>
        </html>
    );
}
