import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="antialiased">
                <ClerkProvider
                    signInFallbackRedirectUrl={
                        process.env
                            .NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
                    }
                    signUpFallbackRedirectUrl={
                        process.env
                            .NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
                    }
                    afterSignOutUrl="/"
                >
                    {children}
                </ClerkProvider>
            </body>
        </html>
    );
}
